import Head from 'next/head'
import { useState } from 'react'

import Navbar from '../Componants/Navbar'
import AdminTopBar from '../Componants/AdminTopBar';
import CreateTeamForm from '../Componants/CreateTeamForm';
import CreateMatchForm from '../Componants/CreateMatchForm';

export default function Admin() {
  
  const [showForm, setShowForm] = useState("team");

  return (
    <div className="admin-container">
      <Head>
        <title>European Football Logs | Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <AdminTopBar showForm={showForm} setShowForm={setShowForm}/>
      {showForm === "team" && <CreateTeamForm/>}
      {showForm === "match" && <CreateMatchForm/>}
      
      
      
    </div>
  )
}
