import Head from 'next/head'
import Navbar from '../Componants/Navbar'

export default function Equipes() {
  return (
    <div className="equipes-container">
      <Head>
        <title>European Football Logs | Equipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <h1>Equipes Page</h1>
    </div>
  )
}
